# --- Configura��o do Banco de Dados H2 ---

server.address=0.0.0.0
server.port=8080

# Habilita o console web do H2
#spring.h2.console.enabled=true
# Define a URL para acessar o console
#spring.h2.console.path=/h2-console

# URL de conex�o JDBC. 'mem' significa em mem�ria. 'karaokedb' � o nome do nosso banco.
#spring.datasource.url=jdbc:h2:mem:karaokedb
# Driver JDBC do H2
#spring.datasource.driverClassName=org.h2.Driver
# Usu�rio padr�o do H2
#spring.datasource.username=admin
# Senha (pode deixar em branco, mas � bom definir para o console)
#spring.datasource.password=123

# --- Configura��o do JPA (Hibernate) ---

# Diz ao Hibernate qual "dialeto" SQL usar para se comunicar com o H2
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# MUITO IMPORTANTE: Define como as tabelas do banco ser�o criadas.
# 'update': atualiza o schema (tabelas) se houver mudan�as nos seus @Entity.
# 'create-drop': cria as tabelas ao iniciar e as apaga ao finalizar. �timo para testes.
#spring.jpa.hibernate.ddl-auto=create-drop

# Show SQL for debugging tests
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ===================================================================
# CONFIGURAÇÃO HÍBRIDA (LOCAL vs PRODUÇÃO)
# ===================================================================

# 1. URL DE CONEXÃO
# Lógica: Tenta pegar a URL da nuvem (${DB_URL}). 
# Se não achar (está local), usa o endereço do Docker (:jdbc:postgresql://...)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/karaq}

# 2. USUÁRIO
# Lógica: Tenta pegar ${DB_USERNAME} da nuvem, senão usa 'postgres'
spring.datasource.username=${DB_USERNAME:postgres}

# 3. SENHA
# Lógica: Tenta pegar ${DB_PASSWORD} da nuvem, senão usa 'password123'
spring.datasource.password=${DB_PASSWORD:password123}

# ===================================================================
# JPA & HIBERNATE
# ===================================================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Em produção, mude para false para não poluir os logs do Render
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=false

# --- Configuração do JWT (JSON Web Token) ---

# Chave secreta: Tenta ler da env JWT_SECRET, senão usa o valor padrão de dev
jwt.secret-key=${JWT_SECRET:bWluaGFjaGF2ZXN1cGVyc2VjcmV0YWVjdW1wcmlkYTEyMzQ1Njc4OTA=}
# Tempo de expiração do token em milissegundos (7200000 ms = 2 horas)
jwt.expiration=${JWT_EXPIRATION:7200000}

# ---- API KEY DO YOUTUBE ---- # 

# Lógica: Pega da env YOUTUBE_API_KEY. Se não houver, usa a chave de dev (apenas para debug local)
youtube.api.key=${YOUTUBE_API_KEY:AIzaSyAVAycqwz5UEDrE4cYNByMj4froM_LdBhU}


spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.jackson.charset=UTF-8